spring:
  datasource:

    username: sa
    password:
    url: jdbc:h2:file:\Users\souja\OneDrive\Área de Trabalho\FATEC\Desenvolvimento WEB\Projetos\pobre-abastece-spring\data

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show:
      sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
     ddl-auto: update